### ISSUE TITLE
Replace log string concantenation with placeholders

### ISSUE THREAD

**Issue by SharkFourSix** [zikani03/articulated#1]
It is considered bad practice to concatenate strings when sending to loggers. The recommended way is to use {} placeholder like so:

```java
log.info("Foo is {} and bar is {}.", foo, bar);
```

https://github.com/zikani03/articulated/blob/851ed85a2321c38c3150df2363aa97ae1db439fd/src/main/java/me/zikani/labs/articulated/fetch/ArticleFetcher.java#L57

Might do a PR to improve those :D

**Comment by zikani03** [comment]
Nice, catch.. will fix those if you don't push a PR mwachangu hehe
